// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://liyowspbttryewpccewq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpeW93c3BidHRyeWV3cGNjZXdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5NjA2NTYsImV4cCI6MjA1NDUzNjY1Nn0.XU7vVmEv_VyUOT6nICNuPCChmijz5PLk1uPVRZ1hjxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);